config/routes.rb
Rails.application.routes.draw do
  root :to=> "galleries#index"
  resources :galleries do
    resources :paintings;
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	has_many :paintings, :dependent => :destroy 
end

app/models/painting.rb
class Painting < ApplicationRecord
	belongs_to :gallery
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end
  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to galleries_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    redirect_to galleries_path
  end
  def gallery_params
    params.require(:gallery).permit(:name)
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
  end

  def show
  end

  def edit
    
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.find(params[:id])

  end
  def update
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.find(params[:id])
    if @painting.update(painting_params)
      redirect_to gallery_path(@gallery)
    else
      render 'edit'
    end
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @painting = @gallery.paintings.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @painting = @gallery.paintings.new(painting_params)
    if @painting.save
      redirect_to gallery_path(@gallery)
    else
      render 'new'
    end
  end


  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to gallery_path
  end
  def painting_params
    params.require(:painting).permit(:p_name, :name, :image, :gallery_id, :remote_image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/destroy.html.erb
<h1>Galleries#destroy</h1>
<p>Find me in app/views/galleries/destroy.html.erb</p>

app/views/galleries/edit.html.erb
<h1>Galleries#edit</h1>
<p>Find me in app/views/galleries/edit.html.erb</p>

app/views/galleries/index.html.erb
<h1>Gallerie</h1>
<% @galleries.each do |f| %>
<div class="gallery">
	<h2><%= link_to f.name, gallery_path(f) %></h2>
	<br>
	Paintings: <%= f.paintings.size %>
	</div>
	<% end %>
	<%= link_to 'new gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>Create Galleries</h1>

<%= form_for @gallery do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.submit 'create' %>
 <% end %>

app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1><br>
<br>
<div id="paintings">
  <% for painting in @gallery.paintings %>
    <div class="painting">
      <%= image_tag painting.image_url(:thumb).to_s %>
      <div class="name"><%= painting.p_name %></div>
      <div class="actions">
        <%= link_to "edit", edit_gallery_painting_path(@gallery, painting) %> |
        <%= link_to "remove", gallery_painting_path(@gallery, painting), :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>
  <%= link_to "Add a Painting", new_gallery_painting_path(@gallery, @painting) %> |
  <%= link_to "Remove Gallery", @gallery, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Galleries", galleries_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Images</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paintings/destroy.html.erb
<h1>Paintings#destroy</h1>
<p>Find me in app/views/paintings/destroy.html.erb</p>

app/views/paintings/edit.html.erb
<h1>update painting</h1>

<%= form_for ([@gallery, @painting]), :html => {:multipart => true} do |s| %>

  <%= s.label :p_name %>
  <%= s.text_field :p_name %>
  <br><br>

  <%= s.file_field :image %><br><br>

  <%= s.label :remote_image_url, "or image URl" %>
  <%= s.text_field :remote_image_url %><br><br> 

  <%= s.submit 'update' %>
 <% end %>

app/views/paintings/index.html.erb
<h1>Paintings#index</h1>
<p>Find me in app/views/paintings/index.html.erb</p>

app/views/paintings/new.html.erb
<h1>Create paintings</h1>

<%= form_for ([@gallery, @painting]) do |s| %>
  <%= s.label :p_name %>
  <%= s.text_field :p_name %>
  <br><br>
  <%= s.submit 'create' %>
 <% end %>

app/views/paintings/show.html.erb
<h1>Paintings#show</h1>
<p>Find me in app/views/paintings/show.html.erb</p>